# Generated by Django 4.2.2 on 2023-06-23 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0002_flashcard_app_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL),
        ),
    ]
